import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    width: '100%',
  },
  subContainer: {
    width: '60%',
    padding: 10,
    backgroundColor: '#f49d35',
    borderRadius: 10,
    marginBottom: 20,
    alignItems: 'center',
    margin: 50,
    alignSelf: 'center',
  },
  text: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#2C232E',
    margin: 20,
    textAlign: 'center',
  },
  input: {
    width: '80%',
    borderColor: 'gray',
    borderWidth: 1,
    backgroundColor: '#ffffff',
    borderRadius: 10,
  },
  pressable: {
    backgroundColor: '#353cf4',
    padding: 10,
    borderRadius: 10,
    marginTop: 20,
    width: '100%',
    alignItems: 'center',
  },
  boton0:{
    justifyContent: 'center',
    height: 60,
    backgroundColor: '#f49d35',
    padding: 10,
    borderRadius: 10,
    margin: 35,
    width: '60%',
    alignItems: 'center',
  },
  boton1:{
    justifyContent: 'center',
    height: 60,
    backgroundColor: '#d1f435',
    padding: 10,
    borderRadius: 10,
    margin: 35,
    width: '60%',
    alignItems: 'center',
  },
  boton2:{
    justifyContent: 'center',
    height: 60,
    backgroundColor: '#35f438',
    padding: 10,
    borderRadius: 10,
    margin: 35,
    width: '60%',
    alignItems: 'center',
  },
  boton3:{
    justifyContent: 'center',
    height: 60,
    backgroundColor: '#35e7f4',
    padding: 10,
    borderRadius: 10,
    margin: 35,
    width: '60%',
    alignItems: 'center',
  },
  boton4:{
    justifyContent: 'center',
    height: 60,
    backgroundColor: '#8535f4',
    padding: 10,
    borderRadius: 10,
    margin: 35,
    width: '60%',
    alignItems: 'center',
  },
  boton5:{
    justifyContent: 'center',
    height: 60,
    backgroundColor: '#f435ee',
    padding: 10,
    borderRadius: 10,
    margin: 35,
    width: '60%',
    alignItems: 'center',
  },
  boton6:{
    justifyContent: 'center',
    height: 60,
    backgroundColor: '#f43535',
    padding: 10,
    borderRadius: 10,
    margin: 35,
    width: '60%',
    alignItems: 'center',
  },
  boton7:{
    justifyContent: 'center',
    height: 60,
    backgroundColor: '#f4d735',
    padding: 10,
    borderRadius: 10,
    margin: 35,
    width: '60%',
    alignItems: 'center',
  },
});
